routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', function() {
    return view('home');
})->name('home')->middleware('auth');

//Route::get('/agenda', 'AgendaController@index')->name('agenda.index');
Route::resource('agenda', 'AgendaController');
  

app/Agenda.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Agenda extends Model
{
    protected $TABLE = "agendas";
    protected $fillable = [
        'nome',
        'fone_res',
        'fone_cel',
        'dt_nasc',
        'email',
        'facebook',
        'twitter',
        'instagram'
    ];

    protected $dates = [
        'dt_nasc',
        'created_at',
        'updated_at',
    ];
}

app/Http/Controllers/AgendaController.php
<?php

namespace App\Http\Controllers;

use App\Agenda;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;



class AgendaController extends Controller
{
    
    /**
     * index: exibe uma lista dos registros da tabela
     * create: exibe um formulario para cadastrar dados
     * store: recebe os dados do form e envia para o Model gravar na tabela (Instert)
     * edit: exibe o formulario para alteração de dados de um registro
     * update: recebe os dados do form e envia para o Model atualizar na tabela (Update)
     * show: exibe em detalhes os dados de um registro
     * destroy: deleta um registro
     */

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $contatos = Agenda::all();
        return view('agenda.index',compact('contatos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('agenda.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
     
        //$dt_nasc= $this-> formata_data($request->dt_nasc);
        
        DB::table('agendas')->insert([

            'nome'=> $request->nome,
            'fone_res'=> $request->fone_res,
            'fone_cel'=> $request->fone_cel,
            'dt_nasc'=> $request->dt_nasc,
            'email'=> $request->email,
            'facebook'=> $request->facebook,
            'twitter'=> $request->twitter,
            'instagram'=> $request->instagram

        ]);

        //Agenda::create($request->all());
        //return view('agenda.index');
        return redirect()->route('agenda.index');
    }
    public function formata_data($data){

        //dd/mm/aaaa
        $d = substr($data, 6, 4) . "-" . substr($data, 3, 2) . "-" . substr($data, 0, 2);
       
        return $d;

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Agenda  $agenda
     * @return \Illuminate\Http\Response
     */
    public function show(Agenda $agenda)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Agenda  $agenda
     * @return \Illuminate\Http\Response
     */
    public function edit(Agenda $agenda)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Agenda  $agenda
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Agenda $agenda)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Agenda  $agenda
     * @return \Illuminate\Http\Response
     */
    public function destroy(Agenda $agenda)
    {
        //
    }
}

resources/views/agenda/create.blade.php
@extends('adminlte::page')

@section('title', 'Agendal6')

@section('content_header')
<h1>Criação de um novo Contato</h1>
@stop

@section('content')
<form action="{{route('agenda.store') }}" method="POST">
    {{csrf_field()}}
    <div class="panel panel-default">
        <div class="panel-heading">
        <p>Preencha todos os campos obrigatórios.</p>
        </div>
        <div class="panel-body"> 
            <div class="form-group"> 
                <label for="nome">Nome do Contato</label>
                <input type="text" id="nome" name="nome" class="form-control" placeholder="Nome">
            </div>

            <div class="form-group"> 
                <label for="fone_res">Telefone Residencial</label>
                <input type="text" id="fone_res" name="fone_res" class="form-control" placeholder="(00)0000-0000">
            </div>

            <div class="form-group"> 
                <label for="fone_cel">Telefone Celular</label>
                <input type="text" id="fone_cel" name="fone_cel" class="form-control" placeholder="(00)00000-0000">
            </div>

             <div class="form-group"> 
                <label for="dt_nasc">Data de Nascimento</label>
                <input type="date" id="dt_nasc" name="dt_nasc" class="form-control">
            </div>

            <div class="form-group"> 
                <label for="email">Email</label>
                <input type="email" id="email" name="email" class="form-control" placeholder="exemplo@email.com">
            </div>

            <div class="form-group"> 
                <label for="facebook">Facebook</label>
                <input type="text" id="facebook" name="facebook" class="form-control" placeholder="Facebook">
            </div>

            <div class="form-group"> 
                <label for="twitter">Twitter</label>
                <input type="text" id="twitter" name="twitter" class="form-control" placeholder="Twitter">
            </div>

        </div>
            <div class="panel-footer clearfix">
                    <a href="{{ route('agenda.index') }}" class="btn btn-default btn-sm">
                        <i class="fas fa-reply"></i> Voltar
                    </a>

                    <button type="submit" class="btn btn-success btn-sm">
                        <i class="fas fa-save"></i> Gravar
                    </button>
            </div> 
    </div>
</form>
@stop

@section('css')
<link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
<script> console.log('Hi!'); </script>
@stop

resources/views/agenda/edit.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
<h1>Dashboard</h1>
@stop

@section('content')
<p>Welcome to this beautiful admin panel.</p>
@stop

@section('css')
<link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
<script> console.log('Hi!'); </script>
@stop

resources/views/agenda/index.blade.php
@extends('adminlte::page')

@section('title', 'Agenda')

@section('content_header')
<h1><i class="fas fa-address-book"></i> Lista de Agendas</h1>
@stop

@section('content')
<div class="panel panel-default">
    <div class="panel-heading clearfix">
    Relação dos contatos da agenda 
        <div class="pull-right">
            <a href="{{ route('agenda.index') }}" class="btn btn-primary btn-sm"><i class="fas fa-sync"></i> Atualizar a tela</a>
            <a href="{{ route('agenda.create') }}" class="btn btn-success btn-sm"><i class="fas fa-plus"></i> Adcionar novo contato</a>
        </div>
    </div>
    <div class="panel-body">    
        <table id="tabela" class="table table-striped table-bordered table-hover">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Nome</th>
                    <th>Celular</th>
                    <th>Email</th>
                    <th>Ações</th>
                </tr>
            </thead>
            <tbody>
                @foreach($contatos as $contato)
                <tr>
                    <td>{{$contato->id}}</td>
                    <td>{{$contato->nome}}</td>
                    <td>{{$contato->fone_cel}}</td>
                    <td>{{$contato->email}}</td>
                    <td>acoes</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>
@stop

@section('css')
<link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
<script> 
    $(document).ready( function () {
        $("#tabela").DataTable();
    });
</script>
@stop

resources/views/agenda/show.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
<h1>Dashboard</h1>
@stop

@section('content')
<p>Welcome to this beautiful admin panel.</p>
@stop

@section('css')
<link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
<script> console.log('Hi!'); </script>
@stop